version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: knex
    versions:
    - 0.21.16
    - 0.21.17
    - 0.21.18
    - 0.21.19
    - 0.95.0
    - 0.95.1
    - 0.95.2
    - 0.95.3
  - dependency-name: express-validator
    versions:
    - 6.10.0
    - 6.9.2
  - dependency-name: objection
    versions:
    - 2.2.12
    - 2.2.14
  - dependency-name: pg
    versions:
    - 8.5.1
  - dependency-name: chalk
    versions:
    - 4.1.0
